apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-amine
  namespace: todo-app-amine
  labels:
    app: backend-amine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-amine
  template:
    metadata:
      labels:
        app: backend-amine
    spec:
      imagePullSecrets:
        - name: gitlab-registry-cred-amine
      containers:
        - name: backend-amine
          image: registry.gitlab.com/esgi3381238/pj_kubernetes/backend-amine:92bf725c
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: backend-config-amine
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
