apiVersion: v1
kind: Service
metadata:
  name: todo-backend-svc
  namespace: todo-app
  labels:
    app: todo-backend
spec:
  selector:
    app: todo-backend
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  type: ClusterIP
