stages:
- test
- secret-detection
- build
- security
- push
- deploy

variables:
  SECRET_DETECTION_ENABLED: 'true'
  SAST_EXCLUDED_PATHS: "node_modules, dist, build, fichiersMD, coverage"

include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml

test-backend:
  stage: test
  image: node:20-alpine
  cache:
    key: backend-deps
    paths:
      - backend/node_modules/
  script:
    - cd backend
    - npm ci --prefer-offline --no-audit --no-fund
    - npm test

sast:
  stage: test

secret_detection:
  stage: secret-detection

build-backend:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE/todo-backend:$CI_COMMIT_SHORT_SHA ./backend
    - docker push $CI_REGISTRY_IMAGE/todo-backend:$CI_COMMIT_SHORT_SHA

build-frontend:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE/todo-frontend:$CI_COMMIT_SHORT_SHA ./frontend
    - docker push $CI_REGISTRY_IMAGE/todo-frontend:$CI_COMMIT_SHORT_SHA

polaris:
  stage: security
  image: quay.io/fairwinds/polaris:latest
  script:
    - polaris audit --config polaris-config.yaml --audit-path k8s/ --format=pretty --set-exit-code-on-danger
  only:
    - thomas

deploy:
  stage : deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]

  before_script:
    - echo "$KUBE_CONFIG" | base64 -d > /tmp/kubeconfig
    - export KUBECONFIG=/tmp/kubeconfig
  script:
    - kubectl set image deployment/todo-backend todo-backend=$CI_REGISTRY_IMAGE/todo-backend:$CI_COMMIT_SHORT_SHA -n todo-app
    - kubectl set image deployment/todo-frontend todo-frontend=$CI_REGISTRY_IMAGE/todo-frontend:$CI_COMMIT_SHORT_SHA -n todo-app
    - kubectl rollout status deployment/todo-backend -n todo-app
    - kubectl rollout status deployment/todo-frontend -n todo-app
  only:
    - thomas
