stages:
- test
- secret-detection
- build
- security
- push
- deploy

variables:
  SECRET_DETECTION_ENABLED: 'true'

include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml

test-backend:
  stage: test
  image: node:20-alpine
  script:
    - cd backend
    - npm ci
    - npm test

sast:
  stage: test

secret_detection:
  stage: secret-detection
