apiVersion: v1
kind: Service
metadata:
  name: frontend-svc-amine
  namespace: todo-app-amine
  labels:
    app: frontend-amine
spec:
  type: ClusterIP
  selector:
    app: frontend-amine
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
